language: cpp
sudo: required
os:
  - linux
  - osx
osx_image: xcode10.1
compiler:
  - clang
  - gcc
install:
  - sudo -i pip install cpplint
before_script:
  - which cpplint && make -j1 lint
  - which clang-tidy && make -j1 tidy
script:
  - make -j2 all
  - make -j1 test
