language: cpp
sudo: required
os:
  - linux
  - osx
osx_image: xcode10.1
compiler:
  - clang
  - gcc
install:
  - sudo -i pip install cpplint
  - '[ "${TRAVIS_OS_NAME}" == "osx" ] && brew install llvm --with-clang --with-clang-extra-tools || exit 0'
before_script:
  - which cpplint && make -j1 lint || exit 0
  - which clang-tidy && make -j1 tidy || exit 0
script:
  - make -j2 all
  - make -j1 test
