language: cpp
sudo: required
os:
  - linux
  - osx
osx_image: xcode10.1
compiler:
  - clang
  - gcc
install:
  - sudo -i pip install cpplint
  - 'if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install llvm && export CLANG_TIDY="/usr/local/opt/llvm/bin/clang-tidy" && ls "${CLANG_TIDY}"; fi'
before_script:
  - make -j1 lint
  - make -j1 tidy
script:
  - make -j2 all
  - make -j1 test
