language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - g++-7
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
before_install: eval "${MATRIX_EVAL}"
jobs:
  include:
    - stage: analysis
      name: "Static analysis"
      script: make -j1 tidy
    - stage: build
      name: "Build programs"
      script: make -j2 all
    - stage: test
      name: "Test programs"
      script: make -j1 test
